#ifndef UPDATER_ERROR_H
#define UPDATER_ERROR_H
#include "Public/Errors.h"

#define UPD_ERR_SUCCEED							EIMERR_NO_ERROR												//接口操作成功
#define UPD_ERR_INTERFACE_POINTER				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  1)		//获取接口指针失败
#define UPD_ERR_NEW_OPER						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  2)		//使用new操作失败
#define UPD_ERR_CALLBACK_POINT_NULL				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  3)		//回调函数指针为空
#define UPD_ERR_FILE_INFO						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  4)		//文件结构S_EIMFileInfo信息不完全
#define UPD_ERR_RUN_UPDATER_MODULER				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  5)		//运行UPdater.exe模块失败
#define UPD_ERR_UPDATER_DOWNLOAD				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  6)		//更新程序下载失败
#define UPD_ERR_PARAM_POINTER_NULL				MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  7)		//参数指针为空
#define UPD_ERR_DIR_NO_EXISTS					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  8)		//目录不存在
#define UPD_ERR_SETUP_FAIL						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  9)		//安装升级程序失败
#define UPD_ERR_COPY_FILE						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  10)	//文件拷贝失败
#define UPD_ERR_LATEST_VERSION					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  11)	//已经是最新版本
#define UPD_ERR_DIR_SAME						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  12)	//目录相同
#define UPD_ERR_CANCEL_UPGRADE					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  13)	//取消升级
#define UPD_ERR_UDP_TYPE						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  14)	//更新类型错误
#define UPD_ERR_LOAD_XML_FILE					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  15)	//加载XML文件失败
#define UPD_ERR_LOAD_XML_ROOT					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  16)	//加载XML根失败节点
#define UPD_ERR_FILE_CNT						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  17)	//XML文件中路径数量错误
#define UPD_ERR_CREATE_DIR						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  18)	//创建目录失败
#define UPD_ERR_DEL_DIR							MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  19)	//删除目录失败
#define UPD_ERR_EXPORT_RES						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  20)	//导出资源文件失败
#define UPD_ERR_FAIL							MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  21)	//更新失败
#define UPD_ERR_PRO_EXCEPTION					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  22)	//程序异常
#define UPD_ERR_DEL_FILE						MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  23)	//文件删除失败
#define UPD_ERR_OPEN_DB_FAILED					MAKE_SF_EXCEPTION(SEVERITY_ERROR, FACILITY_UPDATER,  24)	//打开数据库失败

#endif